#!/usr/bin/env python3
"""
Project Canada province/territory geometry into compact SVG paths.

Reads pipeline/geo/canada.geojson (WGS84 lon/lat), applies a Lambert
Conformal Conic projection (the standard for Canada), simplifies, and writes
web/src/data/geo.ts exporting { viewBox, paths: { <code>: "<svg d>" } }.

Baking the paths in means the app ships no runtime geo dependency.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEOJSON = ROOT / "pipeline" / "geo" / "canada.geojson"
OUT = ROOT / "web" / "src" / "data" / "geo.ts"

# GeoJSON "name" -> jurisdiction code (matches build_data.py)
NAME_TO_CODE = {
    "Ontario": "on", "Quebec": "qc", "British Columbia": "bc", "Alberta": "ab",
    "Manitoba": "mb", "Saskatchewan": "sk", "Nova Scotia": "ns", "New Brunswick": "nb",
    "Newfoundland and Labrador": "nl", "Prince Edward Island": "pe",
    "Yukon Territory": "yt", "Northwest Territories": "nt", "Nunavut": "nu",
}

# Lambert Conformal Conic parameters for Canada.
LAT1, LAT2, LAT0, LON0 = 49.0, 77.0, 49.0, -96.0
CANVAS_W, PAD = 960.0, 12.0
MIN_PX = 0.8       # drop points closer than this to the previous kept point
MIN_RING_PTS = 8   # drop tiny rings (small islands) with fewer points than this


def lcc(lon: float, lat: float) -> tuple[float, float]:
    p1, p2, p0 = map(math.radians, (LAT1, LAT2, LAT0))
    lam, phi, lam0 = math.radians(lon), math.radians(lat), math.radians(LON0)
    phi = max(min(phi, math.radians(89.9)), math.radians(-89.9))
    n = math.log(math.cos(p1) / math.cos(p2)) / math.log(
        math.tan(math.pi / 4 + p2 / 2) / math.tan(math.pi / 4 + p1 / 2)
    )
    F = math.cos(p1) * math.tan(math.pi / 4 + p1 / 2) ** n / n
    rho = F / math.tan(math.pi / 4 + phi / 2) ** n
    rho0 = F / math.tan(math.pi / 4 + p0 / 2) ** n
    x = rho * math.sin(n * (lam - lam0))
    y = rho0 - rho * math.cos(n * (lam - lam0))
    return x, y


def iter_polygons(geom: dict):
    if geom["type"] == "Polygon":
        yield geom["coordinates"]
    elif geom["type"] == "MultiPolygon":
        yield from geom["coordinates"]


def main() -> None:
    data = json.loads(GEOJSON.read_text(encoding="utf-8"))

    # Project every feature into raw LCC space and record bounds.
    projected: dict[str, list[list[tuple[float, float]]]] = {}
    minx = miny = math.inf
    maxx = maxy = -math.inf
    for feat in data["features"]:
        code = NAME_TO_CODE.get(feat["properties"].get("name"))
        if not code:
            continue
        rings: list[list[tuple[float, float]]] = []
        for poly in iter_polygons(feat["geometry"]):
            for ring in poly:
                pts = [lcc(lon, lat) for lon, lat in ring]
                rings.append(pts)
                for x, y in pts:
                    minx, miny = min(minx, x), min(miny, y)
                    maxx, maxy = max(maxx, x), max(maxy, y)
        projected[code] = rings

    scale = (CANVAS_W - 2 * PAD) / (maxx - minx)
    height = (maxy - miny) * scale + 2 * PAD

    def to_px(pt: tuple[float, float]) -> tuple[float, float]:
        x, y = pt
        px = PAD + (x - minx) * scale
        py = PAD + (maxy - y) * scale  # flip: north is up
        return round(px, 1), round(py, 1)

    paths: dict[str, str] = {}
    for code, rings in projected.items():
        segments: list[str] = []
        for ring in rings:
            px_ring = [to_px(p) for p in ring]
            # Distance-based decimation.
            kept = [px_ring[0]]
            for p in px_ring[1:]:
                lx, ly = kept[-1]
                if abs(p[0] - lx) + abs(p[1] - ly) >= MIN_PX:
                    kept.append(p)
            if len(kept) < MIN_RING_PTS:
                continue
            d = "M" + " ".join(f"{x},{y}" for x, y in kept) + "Z"
            segments.append(d)
        paths[code] = "".join(segments)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTO-GENERATED by pipeline/build_map.py — do not edit by hand.",
        "// Canada province/territory outlines, Lambert Conformal Conic projection.",
        f"export const viewBox = \"0 0 {int(CANVAS_W)} {int(round(height))}\";",
        "export const paths: Record<string, string> = {",
    ]
    for code, d in paths.items():
        lines.append(f"  {code}: {json.dumps(d)},")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    kb = OUT.stat().st_size / 1024
    print(f"Wrote {OUT} ({kb:.0f} KB) with {len(paths)} regions, viewBox 0 0 {int(CANVAS_W)} {int(round(height))}")


if __name__ == "__main__":
    main()
